name: destroy-all-the-things

trigger: none

variables:
  - group: aws-keys
  - name: AWS_REGION
    value: eu-central-1 # This value was modified by the initial-setup python script
  - name: APP_NAME
    value: ngao-nghe # This value was modified by the initial-setup python script

pool:
#  vmImage: 'ubuntu-latest' 
  # If you are using a self-hosted agent, comment out the previous line and uncomment the following three
  name: default # Insert here the name of the agent pool you created
  demands:
    - agent.name -equals worker-0 # Insert here the name of the agent you created

jobs:
- job: DeleteAWSInfrastructure
  displayName: 'Delete AWS infrastructure'
  steps:
  - task: TerraformInstaller@1
    displayName: Install terraform
    inputs:
      terraformVersion: '1.4.6'

  - task: TerraformCLI@1
    displayName: 'Terraform Init'
    inputs:
      command: init
      workingDirectory: 'terraform/aws'
      backendType: aws
      backendServiceAws: aws
      providerServiceAws: 'aws'
      providerAwsRegion: $(AWS_REGION)

  - task: TerraformCLI@1
    displayName: 'Terraform Destroy AWS Infra'
    inputs:
      command: destroy
      workingDirectory: 'terraform/aws'
      providerServiceAws: 'aws'
      providerAwsRegion: $(AWS_REGION) 
    continueOnError: true
